config/routes.rb
Rails.application.routes.draw do
  root 'dashboards#show'
  get 'dashboards/show', to: 'dashboards#show'

  resources :shouts, only: [:create] do
    member do 
      post 'like', to: "likes#create"
      delete 'unlike', to: "likes#destroy"
    end
  end

  resources :users, only: %i[new create show edit update] do
    resources :followers, only: [:index]
    member do
      post 'follow', to: "followed_users#create"
      post 'unfollow', to: "followed_users#destroy"
    end
  end

  get 'signin', to: 'sessions#new'
  get 'signup', to: 'users#new'
  post 'signin', to: 'sessions#create'
  delete 'signout', to: 'sessions#destroy'
end

app/controllers/dashboards_controller.rb
# frozen_string_literal: true

class DashboardsController < ApplicationController
  def show
    @shout = Shout.new
    @shouts = Shout.all
  end
end

app/helpers/dashboards_helper.rb
# frozen_string_literal: true

module DashboardsHelper
end

app/views/dashboards/show.html.erb
<h1>Dashboard</h1>
<%= form_with(model: @shout, url: shouts_path) do |form| %>
  <% if @shout.errors.any? %>
    <h4 style="color:red">
      <%= "The following #{pluralize(@shout.errors.count, 'error')} prevented text shout from being created" %>
    </h4>
    <ul style="color:red">
      <% @shout.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  <% end %>
  <div class= "form-group">
    <%= form.hidden_field :shoutable_type, value: "TextShout" %>
    <%= form.fields_for :shoutable do |shoutable_form| %>
      <%= shoutable_form.label :body %>
      <%= shoutable_form.text_area :body, placeholder: "Shout here!", required: true, class: "form-control" %>
  </div>
  <p>
  <%= shoutable_form.submit "Shout!", class: "btn btn-outline-primary my-2" %>
  </p>
  <% end %>

<% end %>

<%= form_with(model: @shout, url: shouts_path) do |form| %>
  <% if @shout.errors.any? %>
    <h4 style="color:red">
      <%= "The following #{pluralize(@shout.errors.count, 'error')} prevented photo shout from being created" %>
    </h4>
    <ul style="color:red">
      <% @shout.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  <% end %>
  <div>
    <%= form.hidden_field :shoutable_type, value: "PhotoShout" %>
    <%= form.fields_for :shoutable do |shoutable_form| %>
      <%= shoutable_form.file_field :image, required: true %>
  </div>
  <p>
  <%= shoutable_form.submit "Shout!", class: "btn btn-outline-primary my-2" %>
  </p>
  <% end %>

<% end %>

<h3 style="color:green"> Shouts </h3>
<% @shouts.each do |shout| %>
  <div>
    <%= avatar(shout.user) %>
    <%= link_to(shout.username, user_path(shout.user)) %>
    <%= render shout.shoutable %>
    <%= "Updated #{time_ago_in_words(shout.updated_at)} ago" %>
    <%= like_button(shout) %>
  </div>
  <hr/>
<% end %>